In [2]:
import pandas
import numpy


from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
from IPython.core.formatters import HTMLFormatter

In [3]:
indices = pandas.read_csv('Datasets/scratch/All_Dates_RGB_Indices(in).csv')

In [4]:
indices_2020 = indices[indices['Year'] == 2020].copy(deep=True)
indices_2021 = indices[indices['Year'] == 2021].copy(deep=True)
indices_2022 = indices[indices['Year'] == 2022].copy(deep=True)



In [5]:
indices_2020.to_csv("2020_indices.csv")
indices_2021.to_csv("2021_indices.csv")
indices_2022.to_csv("2022_indices.csv")
# pandas.DataFrame(indices['Plot'].value_counts()).to_csv("plot_unique.csv")

In [6]:
plots = [
"Plot1",
"Plot1025",
"Plot1137",
"Plot1138",
"Plot1139",
"Plot1140",
"Plot1141",
"Plot1142",
"Plot1143",
"Plot1144",
"Plot1145",
"Plot1146",
"Plot1147",
"Plot1148",
"Plot1149",
"Plot1150",
"Plot1151",
"Plot1152",
"Plot1153",
"Plot1154",
"Plot1155",
"Plot1156",
"Plot1157",
"Plot1158",
"Plot1159",
"Plot1160",
"Plot1161",
"Plot1162",
"Plot1163",
"Plot1164",
"Plot1165",
"Plot1166",
"Plot1167",
"Plot1168",
"Plot1169",
"Plot1170",
"Plot1171",
"Plot1172",
"Plot1173",
"Plot1174",
"Plot1175",
"Plot1176",
"Plot1177",
"Plot1178",
"Plot1179",
"Plot1180",
"Plot1181",
"Plot1182",
"Plot1183",
"Plot1184",
"Plot1185",
"Plot1186",
"Plot1187",
"Plot1188",
"Plot1189",
"Plot1190",
"Plot1191",
"Plot1192",
"Plot1193",
"Plot1194",
"Plot1195",
"Plot1196",
"Plot1197",
"Plot1198",
"Plot1199",
"Plot1200",
"Plot1201",
"Plot1202"
]

In [7]:
interest = indices[indices['Plot'].isin(plots)]
interest.to_csv("interest.csv", index=False)

In [8]:
numpy.unique(indices_2021['Plot'].value_counts())

array([5])

In [9]:
indices_2021['Date'].value_counts()

Date
6082021    1078
6162021    1078
6222021    1078
6302021    1078
7122021    1078
Name: count, dtype: int64

In [10]:
indices_2021['Plot'] = [s.replace('Plot', '') for s in indices_2021['Plot']]
indices_2022['Plot'] = [s.replace('Plot', '') for s in indices_2022['Plot']]
indices_2021['Plot'].to_csv("unique_plots_2021.csv")
indices_2022['Plot'].to_csv("unique_plots_2022.csv")

In [11]:
indices_2022['Date'].value_counts()

Date
6102022    938
6152022    938
6232022    938
6282022    938
7052022    938
7132022    938
7182022    938
Name: count, dtype: int64

In [69]:
missing_2021 = []
missing_2022 = []

for val in range(1, 1121):
    if val not in indices_2021['Plot'].values.astype(numpy.int32):
        missing_2021.append(val)

val = []

for val in range(1, 1147):
    if val not in indices_2022['Plot'].values.astype(numpy.int32):
        missing_2022.append(val)

In [70]:
len(missing_2021)

42

In [71]:
len(missing_2022)

208

In [72]:
len(indices_2022)

6566

In [73]:
len(numpy.unique(indices_2022['Plot']))

938

In [17]:
dates = numpy.unique(indices_2022['Date'])

plot_counts = []

for date in dates:
    plot_counts.append(numpy.unique(indices_2022[indices_2022['Date'] == date]['Plot']))

# plot_counts = indices_2022[indices_2022['Date'].isin(dates)]

print(dates)

# set(plot_counts[0]) == set(plot_counts[1]) == set(plot_counts[2]) == set(plot_counts[3]) == set(plot_counts[4]) == set(plot_counts[5]) == set(plot_counts[6])


[6102022 6152022 6232022 6282022 7052022 7132022 7182022]


In [18]:
set(plot_counts[0])

{'1000',
 '1001',
 '1002',
 '1003',
 '1004',
 '1005',
 '1006',
 '1007',
 '1008',
 '1009',
 '1010',
 '1011',
 '1012',
 '1013',
 '1014',
 '1026',
 '1027',
 '1028',
 '1029',
 '1030',
 '1031',
 '1032',
 '1033',
 '1034',
 '1035',
 '1036',
 '1037',
 '1038',
 '1039',
 '1040',
 '1041',
 '1042',
 '1043',
 '1044',
 '1056',
 '1057',
 '1058',
 '1059',
 '106',
 '1060',
 '1061',
 '1062',
 '1063',
 '1064',
 '1065',
 '1066',
 '1067',
 '1068',
 '1069',
 '107',
 '1070',
 '1071',
 '1072',
 '1073',
 '1074',
 '1075',
 '108',
 '1089',
 '109',
 '1090',
 '1091',
 '1092',
 '1093',
 '1094',
 '1095',
 '1096',
 '1097',
 '1098',
 '1099',
 '110',
 '1100',
 '1101',
 '1102',
 '1103',
 '1104',
 '1105',
 '111',
 '112',
 '1121',
 '1122',
 '1123',
 '1124',
 '1125',
 '1126',
 '1127',
 '1128',
 '1129',
 '113',
 '1130',
 '1131',
 '1132',
 '1133',
 '1134',
 '1135',
 '1136',
 '114',
 '115',
 '116',
 '117',
 '118',
 '119',
 '120',
 '121',
 '122',
 '123',
 '124',
 '137',
 '138',
 '139',
 '140',
 '141',
 '142',
 '143',
 '144',
 

In [19]:
len_diff = len(missing_2022) - len(missing_2021)

missing_2021.extend([None] * len_diff)

pandas.DataFrame({'missing_2021': missing_2021, 'missing_2022': missing_2022}).to_csv("missing_plots.csv")

In [20]:
len(set(missing_2021).intersection(set(missing_2022)))

37

In [21]:
len(set(missing_2021).difference(set(missing_2022)))

6

In [22]:
len(set(missing_2022).difference(set(missing_2021)))

171

In [68]:
numpy.sort(numpy.unique(indices_2022['Plot'].values.astype(numpy.int32)))

array([  15,   16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
         26,   27,   28,   29,   30,   31,   45,   46,   47,   48,   49,
         50,   51,   52,   53,   54,   55,   56,   57,   58,   59,   60,
         61,   62,   75,   76,   77,   78,   79,   80,   81,   82,   83,
         84,   85,   86,   87,   88,   89,   90,   91,   92,   93,  106,
        107,  108,  109,  110,  111,  112,  113,  114,  115,  116,  117,
        118,  119,  120,  121,  122,  123,  124,  137,  138,  139,  140,
        141,  142,  143,  144,  145,  146,  147,  148,  149,  150,  151,
        152,  153,  154,  155,  166,  167,  168,  169,  170,  171,  172,
        173,  174,  175,  176,  177,  178,  179,  180,  181,  182,  183,
        184,  185,  186,  196,  197,  198,  199,  200,  201,  202,  203,
        204,  205,  206,  207,  208,  209,  210,  211,  212,  213,  214,
        215,  216,  217,  226,  227,  228,  229,  230,  231,  232,  233,
        234,  235,  236,  237,  238,  239,  240,  2

In [65]:
indices_2022[indices_2022['Plot'] == '15']

Unnamed: 0 Plot  Year     Date     Red    Green    Blue         BI  \
1197         1198   15  2022  6102022  60.912   88.170  55.967  69.800969   
2135         2136   15  2022  6152022  35.686   56.653  34.761  43.556018   
7909         7910   15  2022  6232022  64.829   93.072  59.369  73.914082   
8847         8848   15  2022  6282022  41.343   63.844  36.117  48.613228   
12203       12204   15  2022  7052022  70.018  106.270  64.331  82.329239   
15559       15560   15  2022  7132022  73.832  108.900  68.336  85.596307   
16497       16498   15  2022  7182022  65.645   89.794  56.588  72.051903   

            GLI     NGRDI  ...       ExR       ExB       ExGR     MGRVI  \
1197   0.202787  0.182839  ... -0.014110 -0.047872  59.475110  0.353849   
2135   0.233242  0.227065  ... -0.052656 -0.062845  42.911656  0.431865   
7909   0.199606  0.178865  ... -0.010638 -0.045820  61.956638  0.346640   
8847   0.244838  0.213914  ... -0.042205 -0.093983  50.270205  0.409108   
12203  0.225406  0.205641  ... -0.034265 -0.067354  78.225265  0.394595   
15559  0.210108  0.191909  ... -0.022047 -0.052693  75.654047  0.370185   
16497  0.190030  0.155360  ...  0.009947 -0.049856  57.345053  0.303397   

          RGBVI      GRRI       VEG  Range  Row  Mean.Yld.bu.ac  
1197   0.390314  1.447498  1.488890     37   15      256.941874  
2135   0.442486  1.587541  1.601486     37   15      256.941874  
7909   0.384739  1.435654  1.478337     37   15      256.941874  
8847   0.463774  1.544252  1.615333     37   15      256.941874  
12203  0.429747  1.517753  1.561176     37   15      256.941874  
15559  0.403075  1.474970  1.513458     37   15      256.941874  
16497  0.369193  1.367873  1.437198     37   15      256.941874  

[7 rows x 23 columns]

In [ ]:
len